# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/rust"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    groups:
      all:
        patterns:
          - "*"

  - package-ecosystem: "helm"
    directory: "/helm"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
