[package]
name = "monster-stats"
version = "0.1.0"
edition = "2024"

[dependencies]
rustemon = "4.2.0"
strum = "0.27.1"
strum_macros = "0.27.1"
tokio = { version = "1.44.2", features = ["full"] }

[[bin]]
name = "monster-stats"
path = "src/main.rs"
