on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4.2.2

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1.0.7
      with:
        toolchain: stable
        default: true

    - name: Cache Rust Build
      uses: Swatinem/rust-cache@v2.7.8

    - name: Test
      uses: actions-rs/cargo@v1.0.3
      with:
        command: test
        args: >
          --manifest-path rust/Cargo.toml
          --all-targets
          --all-features
