name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    uses: ./.github/workflows/_lint.yml

  test:
    uses: ./.github/workflows/_test.yml

  container:
    needs: 
    - lint
    - test
    uses: ./.github/workflows/_container.yml
    permissions:
      packages: write
