on:
  push:
    branches:
      - main

jobs:
  release-please:
    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}
    runs-on: ubuntu-latest
    steps:
    - uses: google-github-actions/release-please-action@v4
      name: release-please
      with:
        release-type: rust
        path: rust
    permissions:
      contents: write
      pull-requests: write

  release-rust-container:
    runs-on: ubuntu-latest
    if: ${{ jobs.release-please.outputs.releases_created }}
    permissions:
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Create tags for publishing image
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=raw,value=latest
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}

    - name: Build and push image to container registry
      if: github.ref_type == 'tag'
      uses: docker/build-push-action@v6
      env:
        DOCKER_BUILD_RECORD_UPLOAD: false
      with:
        context: rust
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
