on:
  push:
    branches:
      - main

jobs:
  release-please:
    outputs:
      helm_released: ${{ steps.release-please.outputs.helm--release_created }}
      rust_releases: ${{ steps.release-please.outputs.rust--release_created }}
    runs-on: ubuntu-latest
    steps:
    - uses: googleapis/release-please-action@v4
      name: release-please
      with:
        config-file: .github/release-config.json
        manifest-file: .github/.release-manifest.json
    permissions:
      issues: write
      contents: write
      pull-requests: write

  release-rust-container:
    runs-on: ubuntu-latest
    needs: release-please
    if: needs.release-please.outputs.rust_released
    permissions:
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Create tags for publishing image
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=raw,value=latest
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}

    - name: Build and push image to container registry
      if: github.ref_type == 'tag'
      uses: docker/build-push-action@v6
      env:
        DOCKER_BUILD_RECORD_UPLOAD: false
      with:
        context: rust
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  release-helm-chart:
    runs-on: ubuntu-latest
    needs: release-please
    if: needs.release-please.outputs.helm_released
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Helm
      uses: Azure/setup-helm@v4

    - name: Login to chart registry
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io/diamondjoseph/monster-stats --username ${{ github.repository_owner }} --password-stdin

    - name: Package and publish chart
      run: |
        helm dependencies update helm
        helm package helm -d /tmp/
        helm push /tmp/helm*.tgz oci://ghcr.io/diamondjoseph/monster-stats
