name: Renovate
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: renovatebot/github-action@v41.0.21
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
